### ISSUE TITLE
Drop into Storage

### ISSUE THREAD

**Issue by Rustbread** [Abstrusle/Diorite#1]
Hello,
it would be neat if there was possibility to drop items into storage like Chest instead of ground.

Cheers

**Comment by Abstrusle** [comment]
There are already mods which do this, such as various inventory mods (Inventory Profiles being one), and my own mod, Practical Barrels. I feel they would be more appropriate, as transferring items to a chest is better done with relevancy to the chest in mind, rather than a loadout.
